### ISSUE TITLE
towers don't extrude due to zero E length

### ISSUE THREAD

**Issue by PxT** [iamnotachoice/Multi-Extrusion-post-processing-scripts-for-Slic3r#3] opened 2015-07-21 04:31 UTC
I like the idea of this script, and have been trying to understand how it works.  So far my towers are not getting extruded because the lengths are all zero.  Snippet of the post-processed GCODE:

```
; printing square tower with layer height 0.206
G1 X98 Y173 F7800
G1 X98 Y173 F7800
; printing brim
G1 X100 Y175 F7800
G1 E0 F6000
G1 X100 Y185 E0 F3600
G1 X110 Y185 E0 F3600
G1 X110 Y175 E0 F3600
G1 X100 Y175 E0 F3600
G1 X100 Y175 F7800
…
```

These zero-length extrusions are present for the entire file.

Initial GCODE generated with Slic3r 1.2.9, and this is reproducible with any input object.  I haven't yet figured out the full logic flow of the script to understand where the issue is, any hints would be appreciated.

**Comment by makertum** [comment] 2015-07-21 06:19
Thanks for the feedback, I'm sure we can fix this. I need some more info on this:
- Your OS
- the Printer-Settings->Custom G-Codes you used
- have you ticked "Use relative E distances" in Printer Settings -> General?
- are you printing with support material?

I'd like to reproduce the error here, so it would be very helpful if you could send me your Slic3r settings *.ini with the settings used, the stl file used and the g-code you get with the script and the g-code you get without the script for me to compare.

The script ~should~ run fine, I've tested it on many setups by now, all working. Have you done all the steps from the readme.md?

[EDIT:] Ah, the bug you just fixed only reveals itself when printing with support material. Hope it works now for you :)

**Comment by PxT** [comment] 2015-07-21 16:08
Mac OS 10.10.4, Slic3r 1.2.9
Start Gcode:

```
; WIPE TOWER PARAMS
; nozzleDiameter=[nozzle_diameter]
; filamentDiameter=[filament_diameter]
; extrusionWidth=[extrusion_width]
; layerHeight=[layer_height]
; firstLayerHeight=[first_layer_height]
; extrusionMultiplier=[extrusion_multiplier]
; firstLayerExtrusionMultiplier=4
; retractionLength=[retract_length]
; toolChangeRetractionLength=[retract_length_toolchange]
; bedWidth=188
; bedDepth=254
; extruders=3
; wipeTowerX=105
; wipeTowerY=180
; wipeTowerW=10
; wipeTowerH=10
; wipeTowerSpacing=20
; wipeTowerLoops=5
; wipeTowerBrimLoops=7
; wipeOffset=2
; purgeOffset=1.33
; wipeLift=5
; travelLift=1
; purgeAmount=0.5
; retractionFeedrate=[retract_speed]
; travelFeedrate=[travel_speed]
; printFeedrate=[perimeter_speed]
; extrusionFeedrate=25
G28 X0 Y0 Z0 ;  home X, Y & Z
G29 ; probe Z axis
T0
M190 S[first_layer_bed_temperature]
M109 S[first_layer_temperature]
```

Use relative e-distances is ON
No support material

Files:
Slic3r config - https://dl.dropboxusercontent.com/u/68081994/WipeTower/config.ini
2-part STL
https://dl.dropboxusercontent.com/u/68081994/WipeTower/0024b.stl
https://dl.dropboxusercontent.com/u/68081994/WipeTower/0024c.stl

GCODE with no post processing - https://dl.dropboxusercontent.com/u/68081994/WipeTower/NoPostProcessing.gcode
GCODE with post processing - https://dl.dropboxusercontent.com/u/68081994/WipeTower/WithPostProcessing.gcode

Let me know if you can see anything that I am doing wrong.

**Comment by PxT** [comment] 2015-07-21 16:15
Same results with Slic3r 1.1.7
https://dl.dropboxusercontent.com/u/68081994/WipeTower/WithPostProcessing-1.1.7.gcode

**Comment by makertum** [comment] 2015-07-21 16:55
Hey there, thanks for upping the files, I just had a look into it.

The problem is that in config.ini almost all parameters that relate to a extrusion_width are 0.

So, the short fix is to define a non-zero extrusion width in the _Custom Start G-code_ as a wipe tower parameter by replacing the line

```
extrusionWidth=[extrusion_width]
```

with the line

```
extrusionWidth=0.4
```

Of course you can also choose another extrusion width in the wipe tower parameters, it will not affect the print, only the wipe towers. My guess is, that they were 0 because Slic3r treats 0 as a default value for extrusion widths that are not explicitly defined. So the long term fix is adding some functionality to the script that is able to deal with Slic3rs default value 0.

I also notice is that you have a very odd layer height of 0.2064 which should not be a problem but stands out :)

**Comment by PxT** [comment] 2015-07-21 17:39
.2064 is a theoretically-optimal layer height for the 1/4" ACME driven Z axis which my printer uses.  See: http://prusaprinters.org/calculator/#optimallayer

Thanks for the fast analysis of the problem.  extrusionWidth=0 is the default value in recent Slic3r versions (setting 0 = automatic) but it should be possible to account for that in your script. 

I'll test out the workaround later today and let you know.

**Comment by makertum** [comment] 2015-07-21 19:58
Ah, interesting, yeah of course that makes a lot of sense, that's a very good screw.

Since it's the intended use of the script to eat the Slic3r parameters, Interpreting the default 0 as actual 0.0 mm extrusion width is obviously wrong, I just haven't considered that case.

It's easy to fix, I'll do it when i merge your other bugfix. Until then I leave this issue open and wish you happy printing with the workaround :)

**Closed as completed** 2015-12-03 08:04 UTC
